==== Scala command line

[source]
scala> 2+3
res0: Int = 5
scala> "Your answer " + res0
res1: String = Your answer 5
scala> var myAge=31 // can be changed
myAge: Int = 31
scala> val myName="Mariusz" // not to change
myName: String = Mariusz
scala> myName = "Kuba"
<console>:12: error: reassignment to val
       myName = "Kuba
scala> val bigMoney = BigInt("2213123123123")
bigMoney: scala.math.BigInt = 2213123123123
scala> val bigPI = BigDecimal("3.1432131315424134123412432143214312412")
bigPI: scala.math.BigDecimal = 3.1432131315424134123412432143214312412
//Import scala library
scala> import scala.math._
import scala.math._
scala> abs(-7)
res0: Int = 7
scala> ceil(3.45)
res1: Double = 4.0
scala> round(3.45)
res2: Long = 3
scala> floor(3.45)
res3: Double = 3.0
scala> max(1, 5)
res0: Int = 5
scala> min(1, 5)
res1: Int = 1
// http://www.scala-lang.org/api/rc2/scala/math/package.html
scala> var age2 = 23
age2: Int = 23
scala> age2 = "fsfs"
<console>:15: error: type mismatch;
 found   : String("fsfs")
 required: Int
       age2 = "fsfs"
:q

==== Scala in InteliJ.

File -> New project -> SBT

Create ScalaTutorial class

while
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var i = 0
    while (i<10){
      i+=1
      println("i " + i);
    }
  }
}

Do while
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var i = 0
    do {
      println("i " + i);
      i+=1
    } while  (i<10)
  }
}

loop through the lethers
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    val lethers = "ahfweuihfuiweh";
    var i = 0;
    for (i <- 0 until lethers.length){
      println(lethers(i))
    }
  }
}

loop through the lethers
[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    var aList = List("a", "b", "c", "d")
    for(item<-aList){
      println(item)
    }
  }
}

even list

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    var i = 0;
    var evenList = for {i <- 1 to 20
                        if (i % 2) == 0
    } yield i + " zl"
    println(evenList)
  }
}

multiple iteration loop

[source]
for (i<-0 to 8; j<-'a' to 'h'){
      println(String.valueOf(j) + i)
    }

define functions

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    newFunction()
  }
  def newFunction(): Unit ={
    println("hallo world!!")
  }
}

string displaying

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    val name = "Mario"
    val age = 31
    val weight = 80.5;
    println(s"My name is $name")
    println(f"My age is ${age +1} and my weight is $weight.2f")
  }
}

String playing

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    val exString = "Mariusz Saramak"
    println("My 3rd lather is " + exString(3))
    println("My name length " + exString.length)
    println("My name is Mario ?  " + exString.equals("Mario"))
    println("My title is " + "Mgr inż ".concat(exString))
  }
}

Functions

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    def getSum(n1:Int=0, n2:Int=0) : Int = { //default value, return type
     return n1+n2 // retrurn or not return
    }
    val sum = getSum(1, 5);
    println(sum);
    val sum2 = getSum(n2=1, n1=2);
    println(sum2);
    val sum3 = getSum(2);
    println(sum3);
  }
}



