==== Scala command line

[source]
scala> 2+3
res0: Int = 5
scala> "Your answer " + res0
res1: String = Your answer 5
scala> var myAge=31 // can be changed
myAge: Int = 31
scala> val myName="Mariusz" // not to change
myName: String = Mariusz
scala> myName = "Kuba"
<console>:12: error: reassignment to val
       myName = "Kuba
scala> val bigMoney = BigInt("2213123123123")
bigMoney: scala.math.BigInt = 2213123123123
scala> val bigPI = BigDecimal("3.1432131315424134123412432143214312412")
bigPI: scala.math.BigDecimal = 3.1432131315424134123412432143214312412
//Import scala library
scala> import scala.math._
import scala.math._
scala> abs(-7)
res0: Int = 7
scala> ceil(3.45)
res1: Double = 4.0
scala> round(3.45)
res2: Long = 3
scala> floor(3.45)
res3: Double = 3.0
scala> max(1, 5)
res0: Int = 5
scala> min(1, 5)
res1: Int = 1
// http://www.scala-lang.org/api/rc2/scala/math/package.html
scala> var age2 = 23
age2: Int = 23
scala> age2 = "fsfs"
<console>:15: error: type mismatch;
 found   : String("fsfs")
 required: Int
       age2 = "fsfs"
:q

==== Scala in InteliJ.

File -> New project -> SBT

Create ScalaTutorial class

while
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var i = 0
    while (i<10){
      i+=1
      println("i " + i);
    }
  }
}

Do while
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var i = 0
    do {
      println("i " + i);
      i+=1
    } while  (i<10)
  }
}

loop through the lethers
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    val lethers = "ahfweuihfuiweh";
    var i = 0;
    for (i <- 0 until lethers.length){
      println(lethers(i))
    }
  }
}

loop through the lethers
[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    var aList = List("a", "b", "c", "d")
    for(item<-aList){
      println(item)
    }
  }
}

even list

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    var i = 0;
    var evenList = for {i <- 1 to 20
                        if (i % 2) == 0
    } yield i + " zl"
    println(evenList)
  }
}

multiple iteration loop

[source]
for (i<-0 to 8; j<-'a' to 'h'){
      println(String.valueOf(j) + i)
    }

define functions

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    newFunction()
  }
  def newFunction(): Unit ={
    println("hallo world!!")
  }
}

string displaying

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    val name = "Mario"
    val age = 31
    val weight = 80.5;
    println(s"My name is $name")
    println(f"My age is ${age +1} and my weight is $weight.2f")
  }
}

String playing

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    val exString = "Mariusz Saramak"
    println("My 3rd lather is " + exString(3))
    println("My name length " + exString.length)
    println("My name is Mario ?  " + exString.equals("Mario"))
    println("My title is " + "Mgr inż ".concat(exString))
  }
}

Functions

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    def getSum(n1:Int=0, n2:Int=0) : Int = { //default value, return type
     return n1+n2 // retrurn or not return
    }
    val sum = getSum(1, 5);
    println(sum);
    val sum2 = getSum(n2=1, n1=2);
    println(sum2);
    val sum3 = getSum(2);
    println(sum3);
  }
}

functions with variable numbers of params

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    def getSum(n1:Int*) : Int = {
      var sum : Int = 0;
      for (i<- n1){
        sum += i;
      }
      sum
    }
    println(getSum(1, 2, 3))
  }
}

Error ()

[source]
object ScalaTutorial {
  def main(args: Array[String]): Unit = {
    def getSum(n1:Int*) {
      var sum : Int = 0;
      for (i<- n1){
        sum += i;
      }
      sum
    }
    println(getSum(1, 2, 3))
  }
}

Arrays vs BufferArray, Arrays should be used when size is known.

[source]
val myLuckyNumb = Array[Int](20)
myLuckyNumb(0) = 13
println(myLuckyNumb(0))
val myFriends = Array ("Marek", "Tomek", "Krzysiek")
println(myFriends(0))

ArrayBuffer
[source]
val myFriends = ArrayBuffer[String]()
myFriends.insert(0, "Grzegorz")
myFriends += "Michal"
myFriends ++= Array("Agnieszka", "Marta")
myFriends.remove(0);
println(myFriends)

Array filter
[source]
val favNumes = Array(1, 2,3)
val favNumDouble = for(i<-favNumes if i %2 ==0 ) yield i*2
favNumDouble.foreach(println)

Play with array, max, min, reverse, sort
[source]
val array = List(1, 2, 3, 4)
println(array.max)
println(array.min)
println(array.reverse)
println(array.sortWith(_<_))
println(array.mkString(", "))

Play with map
[source]
//immutable map
val employees = Map("Manager" -> "Bob", "Secretary" -> "Ann")
if (employees.contains("Manager")){
   printf("Manager %s\n", employees("Manager"))
}else{
   println("No managers")
}
val customers = collection.mutable.Map("Customer1" -> "Mariusz", "Customer2" -> "Janusz");
customers("Customer1") = "Janek"
for((k, v) <- customers){
   printf("%s is %s \n", k, v)
}

Play with tuple
[source]
//immutable
val tupleMario = (14, "Mariusz Saramak", 10.33f)
printf("%s owes us %.2f \n", tupleMario._2, tupleMario._3)
//iteration
tupleMario.productIterator.foreach{ i => println(i) }

Animal class, constructor, getters, setters
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var azor = new Animal("Azor", 2)
    println(azor.getName() + " " + azor.getAge())

  }
  class Animal(var name: String, var age: Int = 0){
    println("Created new aniaml " + getName())
    setName(name)

    def getName() : String = name
    def getAge() = age
    def setName(name: String): Unit = {
      if (name.matches(".*\\d+.*")){
        this.name = "No name"
      }else{
        this.name= name
      }
    }
  }
}

Add new constructor
[source]
def this(name: String){
    this(name, 3);
}

Companion object
[source]
object Animal {
    private var id = 0;
    def newId(): Int = {
      id += 1
      id
    }
  }

Inheritance
[source]
class Dog(name: String, age:Int, sound:String) extends Animal(name, age) {
    println("Createing dog" + getName())
    def this(name: String) = {
      this(name, 0, "howhow")
    }
    override def toString() : String = {
      name
    }
  }

Abstract class
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var cat = new Cat(2)
    cat.move
  }
  abstract class MovingAnimal(moveSpeed: Double) {
    def move
  }
  class Cat(moveSpeed: Double) extends MovingAnimal(moveSpeed) {
    override def move: Unit = {
      println("cat with move speed " + moveSpeed)
    }
  }
}

Traits
[source]
object ScalaTutorial {
  def main(args: Array[String]) {
    var bird = new Bird("Wrobel")
    var bigBird = new Bird("Wielki ptak") with NoFlayable
    bigBird.fly();
    bird.fly();
  }
  trait Movable {
    def move(): String = {
      "It can move"
    }
  }
  trait Flayable {
    def fly() = {
      println("It can fly")
    }
  }
  trait NoFlayable extends Flayable {
    override def fly() = {
      println("Can not fly")
    }
  }
  trait Soundable {
    def noise()
  }
  class Bird(name: String) extends Movable with Flayable with Soundable {
    override def noise(): Unit = println(s"${name} make noice")
  }
}

Passing function as arg
[source]
def times3(i: Int) = i * 3
def times4(i: Int) = i * 4
def multiply(func: (Int) => Double, i: Int): Double = {
   func(i)
}
println(multiply(times3, 2));

Try,catch,finally
object ScalaTutorial {
  def main(args: Array[String]) {
    val fun10log = math.log10 _
    def times3(i: Int) = i * 3
    def times4(i: Int) = i * 4
    def multiply(func: (Int) => Double, i: Int): Double =
      try {
        func(i)
      }catch {
        case ex : ArithmeticException => { println("don"); Double.PositiveInfinity}
        case ex : NullPointerException => throw ex

      } finally {

      }
    println(multiply(null, 2));
  }
}


